apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  labels:
    name: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      name: selenium-hub
  template:
    metadata:
      labels:
        name: selenium-hub
    spec:
      containers:
        - name: selenium-hub
          image: selenium/hub:4.1.1-20220121
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4444
            - containerPort: 4443
            - containerPort: 4442
            - containerPort: 5557
          env:
            - name: TZ
              value: "Asia/Shanghai"
          volumeMounts:
            - mountPath: "/etc/localtime"
              name: "host-time"
      nodeSelector:
        uiauto-node: "true"
      volumes:
        - name: "host-time"
          hostPath:
            path: "/etc/localtime"

---
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  labels:
    name: selenium-hub
spec:
  type: NodePort
  ports:
    - name: port1
      protocol: TCP
      port: 4442
      targetPort: 4442
    - name: port2
      protocol: TCP
      port: 4443
      targetPort: 4443
    - name: port3
      protocol: TCP
      port: 5557
      targetPort: 5557
    - name: port0
      targetPort: 4444
      port: 4444
      nodePort: 32757
  selector:
    name: selenium-hub
  sessionAffinity: None

